app/warning/__init__.py
from flask import Blueprint

warning = Blueprint('warning',__name__)

from . import views

app/warning/views.py
#coding=utf-8
from flask import render_template, session, redirect, url_for, current_app
from flask import jsonify
from flask import request
from flask.ext.login import login_required
from ..models import WarningType
from .. import db
from . import warning

#订单类型管理
@warning.route('/')
@login_required
def index():
	ordertypes = WarningType.query.order_by('id').all()
	return render_template('warning/index.html',ordertypes=ordertypes)

@warning.route('/add_ordertype',methods=['POST'])
@login_required
def add_ordertype():
	ordertype = WarningType(name=request.form['name'],color=request.form['color'])
	db.session.add(ordertype)
	db.session.commit()
	return redirect(url_for('warning.index'))

@warning.route('/del_ordertype',methods=['POST'])
@login_required
def del_ordertype():
	gids = request.form['gids']
	WarningType.query.filter(WarningType.id.in_(gids.split(','))).delete(synchronize_session=False)
	return redirect(url_for('warning.index'))

@warning.route('/update_ordertype',methods=['POST'])
@login_required
def update_ordertype():
	gid = request.form['id']
	name = request.form['name']
	color = request.form['color']
	WarningType.query.filter_by(id=gid).update({WarningType.name:name, WarningType.color:color})
	db.session.commit()
	return redirect(url_for('warning.index'))

@warning.route('/_get_ordertype/<gid>')
def get_ordertype(gid):
	ordertype = WarningType.query.filter_by(id=gid).first()
	return jsonify(ordertype.to_json())

app/templates/warning/index.html
{% extends "layout.html" %}

{% block head_css %}
  {{ super() }}
  <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='css/colorpicker/bootstrap-colorpicker.min.css') }}">
{% endblock %}


{% block page_content %}

<!-- Right side column. Contains the navbar and content of the page -->
<aside class="right-side">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            备注类型管理
        </h1>
        <ol class="breadcrumb">
            <li><a href="{{ url_for('main.index') }}"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active"><a href="{{ url_for('warning.index') }}">备注类型管理</a></li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">

        <div class="row">
            <div class="col-md-12">
                <div class="box">
                      
                    <div class="box-body">
                        
                        <div class="box-header">
                            <h3 class="box-title">备注类型列表</h3>
                            <span class="pull-right">
                              <button type="button" class="btn btn-success" data-toggle="modal" data-target="#add-user-modal"><i class='fa fa-plus'></i></button>
                              <button type="button" class="btn btn-danger mutiple-delete-user"><i class='fa fa-trash-o'></i></button>
                            </span>
                        </div><!-- /.box-header -->
                        
                          <table class="table table-bordered table-hover">
                              <tr>
                                  <th style="width: 10px">
                                    <input type="checkbox" class="icheckbox_square-blue check-all"/>
                                  </th>
                                  <th style="width: 10px">#</th>
                                  <th>类型名称</th>
                                  <th>颜色</th>
                                  <th style="width: 200px">操作</th>
                              </tr>

                              {% for ordertype in ordertypes %}
                              <tr style="background-color: {% if ordertype.color %}{{ ordertype.color }}{% else %} #0000  {% endif %}">
                                  <td>
                                    <input type="checkbox" value="{{ ordertype.id }}" class="minimal-red check-item"/>
                                   
                                  </td>
                                  <td>{{ ordertype.id }}</td>
                                 
                                  <td>{{ ordertype.name }}</td>
                                  <td>{{ ordertype.color }}</td> 
                                  <td>
                                    
                                        <button type="button" class="btn btn-default edit-user"><i class='fa fa-wrench'></i></button>

                                        
                                        </button>
                                       
                                   
                                  </td>
                              </tr>
                              {% endfor %}
                              
                              
                          </table>
                      </div><!-- /.box-body -->
                      
                  </div>
                </div>
                
                
              </div>
    </section><!-- /.content -->
</aside><!-- /.right-side -->

{% endblock %}

{% block otherdiv %}
 <!-- COMPOSE MESSAGE MODAL -->
<div class="modal fade" id="add-user-modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">新增备注类型 </h4>
            </div>
            <form action="{{ url_for('warning.add_ordertype')}}" method="post">
                <div class="modal-body">
                  <div class="form-group">
                      <div class="input-group">
                          <span class="input-group-addon">类型名称:</span>
                          <input name="name" class="form-control">
                      </div>
                  </div>

                  <div class="form-group">
                      <div class="input-group type-color">
                          <span class="input-group-addon">类型颜色:</span>
                          <input name="color" class="form-control">
                          <span class="input-group-addon"><i></i></span>
                      </div>
                  </div>

                </div>
                <div class="modal-footer clearfix">
                  <button type="submit" class="btn btn-primary">提交</button>
                </div>
            </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->


<div class="modal fade bs-example-modal-sm" id="del-user-modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">删除备注类型 </h4>
            </div>
            <form action="{{ url_for('warning.del_ordertype')}}" method="post">
                <div class="modal-body">
                  是否确认删除这些备注类型
                  <input type="hidden" id="gids" name="gids"/>
                </div>
                <div class="modal-footer clearfix">
                  <button type="submit" class="btn btn-primary">提交</button>
                </div>
            </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->



<div class="modal fade" id="edit-user-modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">编辑备注类型 </h4>
            </div>
            <form action="{{ url_for('warning.update_ordertype')}}" method="post">
                <input name="id" value="" type="hidden" id="edit-id">
                <div class="modal-body">
                  <div class="form-group">
                      <div class="input-group">
                          <span class="input-group-addon">类型名称:</span>
                          <input name="name" id="edit-name" class="form-control">
                      </div>
                  </div>

                  <div class="form-group">
                      <div class="input-group type-color">
                          <span class="input-group-addon">类型颜色:</span>
                          <input name="color" id="edit-color" class="form-control"/>
                          <span class="input-group-addon"><i></i></span>
                      </div>
                  </div>
                 
                  
                </div>
                <div class="modal-footer clearfix">
                  <button type="submit" class="btn btn-primary">提交</button>
                </div>
            </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->


{% endblock %}

{% block foot_js %}
    {{ super() }}
    <script type="text/javascript" src="{{ url_for('static',filename='js/colorpicker/bootstrap-colorpicker.min.js')}}"></script>

<script type="text/javascript">
     $(function() {
        /*
       $(".sidebar-menu > li").removeClass('active');
       $(".sidebar-menu > li").each(
         function(index,element){
           if(index==0){
             //alert(item);
             $(element).addClass('active');
           }
         }
       );
       $(".sidebar .treeview").tree();
       */

       $('.type-color').colorpicker();
       
       //用户table操作
      $(".check-all").on("change",function(event){
         if($(this).prop('checked')){
           $(".check-item").prop('checked',true);
         }else{
           $(".check-item").prop('checked',false);
         }
       });
       
       
       $(".edit-user").on("click",function(){
         selected_id = $(this).parent().siblings().find(':checkbox').val()
         $.getJSON('_get_ordertype/'+selected_id,function(data){
            $('#edit-id').val(data.id);
            $('#edit-name').val(data.name);
            $('#edit-color').val(data.color);
            $('#edit-user-modal').modal();
         });
       });
       
       
       $(".mutiple-delete-user").on("click",function(){
         var item_size = $(".check-item").size();
         var checked_item_size = 0;
         var checked_items = new Array();
         $(".check-item").each(function(index,element){
           if(element.checked){
             checked_item_size++;
             checked_items.push(element);
           }
         });
         if(checked_item_size == 0){
           alert("至少选择一个需要删除的项目");
         }else{            
            uids = $(checked_items).map(function(){return $(this).val()}).get().join();
            $('#gids').val(uids);
            $('#del-user-modal').modal();
         }
       });
      
     });
   </script>

{% endblock %}