app/game/__init__.py
from flask import Blueprint

game = Blueprint('game',__name__)

from . import views

app/game/views.py
#coding=utf-8
from flask import render_template, session, redirect, url_for, current_app
from flask import jsonify
from flask import request
from flask.ext.login import login_required
from ..models import Game,Area,Server
from .. import db
from . import game

#游戏管理
@game.route('/')
@login_required
def games():
	games = Game.query.order_by('id').all()
	return render_template('game/games.html',games=games)

@game.route('/add_game',methods=['POST'])
@login_required
def add_game():
	game = Game(name=request.form['name'])
	db.session.add(game)
	db.session.commit()
	return redirect(url_for('game.games'))

@game.route('/del_game',methods=['POST'])
@login_required
def del_game():
	gids = request.form['gids']
	Game.query.filter(Game.id.in_(gids.split(','))).delete(synchronize_session=False)
	return redirect(url_for('game.games'))

@game.route('/update_game',methods=['POST'])
@login_required
def update_game():
	gid = request.form['id']
	name = request.form['name']
	Game.query.filter_by(id=gid).update({Game.name:name})
	db.session.commit()
	return redirect(url_for('game.games'))

@game.route('/_get_game/<gid>')
def get_game(gid):
	game = Game.query.filter_by(id=gid).first()
	return jsonify(game.to_json())


#区管理

@game.route('/areas/<gid>')
@login_required
def areas(gid):
	game = Game.query.filter_by(id=gid).first()
	areas = Area.query.filter_by(game_id=gid).all()
	return render_template('game/areas.html',game=game,areas=areas)

@game.route('/add_area',methods=['POST'])
@login_required
def add_area():
	gid = request.form['gid']
	area = Area(name=request.form['name'],game_id=gid)
	db.session.add(area)
	db.session.commit()
	return redirect(url_for('game.areas',gid=gid))

@game.route('/del_area',methods=['POST'])
@login_required
def del_area():
	gid = request.form['gid']
	aids = request.form['aids']
	Area.query.filter(Area.id.in_(aids.split(','))).delete(synchronize_session=False)
	return redirect(url_for('game.areas',gid=gid))

@game.route('/update_area',methods=['POST'])
@login_required
def update_area():
	gid = request.form['gid']
	aid = request.form['id']
	name = request.form['name']
	Area.query.filter_by(id=aid).update({Area.name:name})
	db.session.commit()
	return redirect(url_for('game.areas',gid=gid))

@game.route('/_get_area/<aid>')
def get_area(aid):
	area = Area.query.filter_by(id=aid).first()
	return jsonify(area.to_json())



#服务器管理

@game.route('/servers/<gid>/<aid>')
@login_required
def servers(gid,aid):
	game = Game.query.filter_by(id=gid).first()
	area = Area.query.filter_by(id=aid).first()
	servers = Server.query.filter_by(area_id=aid).all()
	return render_template('game/servers.html',game=game,area=area,servers=servers)

@game.route('/add_server',methods=['POST'])
@login_required
def add_server():
	gid = request.form['gid']
	aid = request.form['aid']
	server = Server(name=request.form['name'],area_id=aid)
	db.session.add(server)
	db.session.commit()
	return redirect(url_for('game.servers',gid=gid,aid=aid))
	

@game.route('/del_server',methods=['POST'])
@login_required
def del_server():
	gid = request.form['gid']
	aid = request.form['aid']
	sids = request.form['sids']
	Server.query.filter(Server.id.in_(sids.split(','))).delete(synchronize_session=False)
	return redirect(url_for('game.servers',gid=gid,aid=aid))

@game.route('/update_server',methods=['POST'])
@login_required
def update_server():
	gid = request.form['gid']
	aid = request.form['aid']
	sid = request.form['id']
	name = request.form['name']
	Server.query.filter_by(id=sid).update({Server.name:name})
	db.session.commit()
	return redirect(url_for('game.servers',gid=gid,aid=aid))

@game.route('/_get_server/<sid>')
def get_server(sid):
	server = Server.query.filter_by(id=sid).first()
	return jsonify(server.to_json())

app/templates/game/areas.html
{% extends "layout.html" %}

{% block page_content %}

<!-- Right side column. Contains the navbar and content of the page -->
<aside class="right-side">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            区服管理
            <small>{{ game.name }}</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="{{ url_for('main.index') }}"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active"><a href="{{ url_for('game.games') }}">游戏管理</a></li>
            <li class="active"><a href="{{ url_for('game.areas',gid=game.id) }}">区管理</a></li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">

        <div class="row">
            <div class="col-md-12">
                <div class="box">
                      
                    <div class="box-body">
                        
                        <div class="box-header">
                            <h3 class="box-title">区服简称列表</h3>
                            <span class="pull-right">
                              <button type="button" class="btn btn-success" data-toggle="modal" data-target="#add-user-modal"><i class='fa fa-plus'></i></button>
                              <button type="button" class="btn btn-danger mutiple-delete-user"><i class='fa fa-trash-o'></i></button>
                            </span>
                        </div><!-- /.box-header -->
                        
                          <table class="table table-bordered table-hover">
                              <tr>
                                  <th style="width: 10px">
                                    <input type="checkbox" class="icheckbox_square-blue check-all"/>
                                  </th>
                                  <th style="width: 10px">#</th>
                                  <th>区名称</th>
                                  <th style="width: 200px">操作</th>
                              </tr>

                              {% for area in areas %}
                              <tr>
                                  <td>
                                    <input type="checkbox" value="{{ area.id }}" class="minimal-red check-item"/>
                                   
                                  </td>
                                  <td>{{ area.id }}</td>
                                 
                                  <td>{{ area.name }}</td>
                                  
                                  <td>
                                    
                                        <button type="button" class="btn btn-default edit-user"><i class='fa fa-wrench'></i></button>

                                        <button type="button" class="btn btn-default">
                                          <a href="{{ url_for('game.servers',gid=game.id,aid=area.id)}}"><i class='fa fa-angle-double-down'></i></a>
                                          
                                        </button>
                                       
                                   
                                  </td>
                              </tr>
                              {% endfor %}
                              
                              
                          </table>
                      </div><!-- /.box-body -->
                      
                  </div>
                </div>
                
                
              </div>
    </section><!-- /.content -->
</aside><!-- /.right-side -->

{% endblock %}

{% block otherdiv %}
 <!-- COMPOSE MESSAGE MODAL -->
<div class="modal fade" id="add-user-modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">新增 </h4>
            </div>
            <form action="{{ url_for('game.add_area')}}" method="post">
                <input type="hidden" name="gid" value="{{ game.id }}"/>
                <div class="modal-body">
                  <div class="form-group">
                      <div class="input-group">
                          <span class="input-group-addon">区名称:</span>
                          <input name="name" class="form-control">
                      </div>
                  </div>

                </div>
                <div class="modal-footer clearfix">
                  <button type="submit" class="btn btn-primary">提交</button>
                </div>
            </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->


<div class="modal fade bs-example-modal-sm" id="del-user-modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">删除区 </h4>
            </div>
            <form action="{{ url_for('game.del_area')}}" method="post">
            <input type="hidden" name="gid" value="{{ game.id }}"/>
                <div class="modal-body">
                  是否确认删除这些区
                  <input type="hidden" id="gids" name="aids"/>
                </div>
                <div class="modal-footer clearfix">
                  <button type="submit" class="btn btn-primary">提交</button>
                </div>
            </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->



<div class="modal fade" id="edit-user-modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">编辑区 </h4>
            </div>
            <form action="{{ url_for('game.update_area')}}" method="post">
                <input type="hidden" name="gid" value="{{ game.id }}"/>
                <input name="id" value="" type="hidden" id="edit-id">
                <div class="modal-body">
                  <div class="form-group">
                      <div class="input-group">
                          <span class="input-group-addon">区名称:</span>
                          <input name="name" id="edit-name" class="form-control">
                      </div>
                  </div>
                 
                  
                </div>
                <div class="modal-footer clearfix">
                  <button type="submit" class="btn btn-primary">提交</button>
                </div>
            </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->


{% endblock %}

{% block foot_js %}
    {{ super() }}

<script type="text/javascript">
     $(function() {
        /*
       $(".sidebar-menu > li").removeClass('active');
       $(".sidebar-menu > li").each(
         function(index,element){
           if(index==0){
             //alert(item);
             $(element).addClass('active');
           }
         }
       );
       $(".sidebar .treeview").tree();
       */
       
       //用户table操作
       $(".check-all").on("change",function(event){
         if($(this).prop('checked')){
           $(".check-item").prop('checked',true);
         }else{
           $(".check-item").prop('checked',false);
         }
       });
       
       
       $(".edit-user").on("click",function(){
         selected_id = $(this).parent().siblings().find(':checkbox').val()
         $.getJSON('/game/_get_area/'+selected_id,function(data){
            $('#edit-id').val(data.id);
            $('#edit-name').val(data.username);
            $('#edit-user-modal').modal();
         });
       });
       
       
       $(".mutiple-delete-user").on("click",function(){
         var item_size = $(".check-item").size();
         var checked_item_size = 0;
         var checked_items = new Array();
         $(".check-item").each(function(index,element){
           if(element.checked){
             checked_item_size++;
             checked_items.push(element);
           }
         });
         if(checked_item_size == 0){
           alert("至少选择一个需要删除的项目");
         }else{            
            uids = $(checked_items).map(function(){return $(this).val()}).get().join();
            $('#gids').val(uids);
            $('#del-user-modal').modal();
         }
       });
      
     });
   </script>

{% endblock %}

app/templates/game/games.html
{% extends "layout.html" %}

{% block page_content %}

<!-- Right side column. Contains the navbar and content of the page -->
<aside class="right-side">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            游戏管理
        </h1>
        <ol class="breadcrumb">
            <li><a href="{{ url_for('main.index') }}"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active"><a href="{{ url_for('game.games') }}">游戏管理</a></li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">

        <div class="row">
            <div class="col-md-12">
                <div class="box">
                      
                    <div class="box-body">
                        
                        <div class="box-header">
                            <h3 class="box-title">游戏列表</h3>
                            <span class="pull-right">
                              <button type="button" class="btn btn-success" data-toggle="modal" data-target="#add-user-modal"><i class='fa fa-plus'></i></button>
                              <button type="button" class="btn btn-danger mutiple-delete-user"><i class='fa fa-trash-o'></i></button>
                            </span>
                        </div><!-- /.box-header -->
                        
                          <table class="table table-bordered table-hover">
                              <tr>
                                  <th style="width: 10px">
                                    <input type="checkbox" class="icheckbox_square-blue check-all"/>
                                  </th>
                                  <th style="width: 10px">#</th>
                                  <th>游戏名称</th>
                                  <th style="width: 200px">操作</th>
                              </tr>

                              {% for game in games %}
                              <tr>
                                  <td>
                                    <input type="checkbox" value="{{ game.id }}" class="minimal-red check-item"/>
                                   
                                  </td>
                                  <td>{{ game.id }}</td>
                                 
                                  <td>{{ game.name }}</td>
                                  
                                  <td>
                                    
                                        <button type="button" class="btn btn-default edit-user"><i class='fa fa-wrench'></i></button>

                                        <button type="button" class="btn btn-default">
                                          <a href="{{ url_for('game.areas',gid=game.id) }}"><i class='fa fa-angle-double-down'></i></a>
                                          
                                        </button>
                                       
                                   
                                  </td>
                              </tr>
                              {% endfor %}
                              
                              
                          </table>
                      </div><!-- /.box-body -->
                      
                  </div>
                </div>
                
                
              </div>
    </section><!-- /.content -->
</aside><!-- /.right-side -->

{% endblock %}

{% block otherdiv %}
 <!-- COMPOSE MESSAGE MODAL -->
<div class="modal fade" id="add-user-modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">新增游戏 </h4>
            </div>
            <form action="{{ url_for('game.add_game')}}" method="post">
                <div class="modal-body">
                  <div class="form-group">
                      <div class="input-group">
                          <span class="input-group-addon">游戏名称:</span>
                          <input name="name" class="form-control">
                      </div>
                  </div>

                </div>
                <div class="modal-footer clearfix">
                  <button type="submit" class="btn btn-primary">提交</button>
                </div>
            </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->


<div class="modal fade bs-example-modal-sm" id="del-user-modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">删除游戏 </h4>
            </div>
            <form action="{{ url_for('game.del_game')}}" method="post">
                <div class="modal-body">
                  是否确认删除这些游戏
                  <input type="hidden" id="gids" name="gids"/>
                </div>
                <div class="modal-footer clearfix">
                  <button type="submit" class="btn btn-primary">提交</button>
                </div>
            </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->



<div class="modal fade" id="edit-user-modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">编辑游戏 </h4>
            </div>
            <form action="{{ url_for('game.update_game')}}" method="post">
                <input name="id" value="" type="hidden" id="edit-id">
                <div class="modal-body">
                  <div class="form-group">
                      <div class="input-group">
                          <span class="input-group-addon">游戏名称:</span>
                          <input name="name" id="edit-name" class="form-control">
                      </div>
                  </div>
                 
                  
                </div>
                <div class="modal-footer clearfix">
                  <button type="submit" class="btn btn-primary">提交</button>
                </div>
            </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->


{% endblock %}

{% block foot_js %}
    {{ super() }}

<script type="text/javascript">
     $(function() {
        /*
       $(".sidebar-menu > li").removeClass('active');
       $(".sidebar-menu > li").each(
         function(index,element){
           if(index==0){
             //alert(item);
             $(element).addClass('active');
           }
         }
       );
       $(".sidebar .treeview").tree();
       */
       
       //用户table操作
      $(".check-all").on("change",function(event){
         if($(this).prop('checked')){
           $(".check-item").prop('checked',true);
         }else{
           $(".check-item").prop('checked',false);
         }
       });
       
       
       $(".edit-user").on("click",function(){
         selected_id = $(this).parent().siblings().find(':checkbox').val()
         $.getJSON('_get_game/'+selected_id,function(data){
            $('#edit-id').val(data.id);
            $('#edit-name').val(data.username);
            $('#edit-user-modal').modal();
         });
       });
       
       
       $(".mutiple-delete-user").on("click",function(){
         var item_size = $(".check-item").size();
         var checked_item_size = 0;
         var checked_items = new Array();
         $(".check-item").each(function(index,element){
           if(element.checked){
             checked_item_size++;
             checked_items.push(element);
           }
         });
         if(checked_item_size == 0){
           alert("至少选择一个需要删除的项目");
         }else{            
            uids = $(checked_items).map(function(){return $(this).val()}).get().join();
            $('#gids').val(uids);
            $('#del-user-modal').modal();
         }
       });
      
     });
   </script>

{% endblock %}

app/templates/game/servers.html
{% extends "layout.html" %}

{% block page_content %}

<!-- Right side column. Contains the navbar and content of the page -->
<aside class="right-side">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            服务器管理
            <small>{{ game.name }}-{{ area.name }}</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="{{ url_for('main.index') }}"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class=""><a href="{{ url_for('game.games') }}">游戏管理</a></li>
            <li class=""><a href="{{ url_for('game.areas',gid=game.id) }}">区管理</a></li>
            <li class="active"><a href="{{ url_for('game.servers',gid=game.id, aid=area.id) }}">服务器管理</a></li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">

        <div class="row">
            <div class="col-md-12">
                <div class="box">
                      
                    <div class="box-body">
                        
                        <div class="box-header">
                            <h3 class="box-title">服务器列表</h3>
                            <span class="pull-right">
                              <button type="button" class="btn btn-success" data-toggle="modal" data-target="#add-user-modal"><i class='fa fa-plus'></i></button>
                              <button type="button" class="btn btn-danger mutiple-delete-user"><i class='fa fa-trash-o'></i></button>
                            </span>
                        </div><!-- /.box-header -->
                        
                          <table class="table table-bordered table-hover">
                              <tr>
                                  <th style="width: 10px">
                                    <input type="checkbox" class="icheckbox_square-blue check-all"/>
                                  </th>
                                  <th style="width: 10px">#</th>
                                  <th>服务器名称</th>
                                  <th style="width: 200px">操作</th>
                              </tr>

                              {% for server in servers %}
                              <tr>
                                  <td>
                                    <input type="checkbox" value="{{ server.id }}" class="minimal-red check-item"/>
                                   
                                  </td>
                                  <td>{{ server.id }}</td>
                                 
                                  <td>{{ server.name }}</td>
                                  
                                  <td>
                                    
                                        <button type="button" class="btn btn-default edit-user"><i class='fa fa-wrench'></i></button>

                                       
                                          
                                        </button>
                                       
                                   
                                  </td>
                              </tr>
                              {% endfor %}
                              
                              
                          </table>
                      </div><!-- /.box-body -->
                      
                  </div>
                </div>
                
                
              </div>
    </section><!-- /.content -->
</aside><!-- /.right-side -->

{% endblock %}

{% block otherdiv %}
 <!-- COMPOSE MESSAGE MODAL -->
<div class="modal fade" id="add-user-modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">新增 </h4>
            </div>
            <form action="{{ url_for('game.add_server')}}" method="post">
                <input type="hidden" name="gid" value="{{ game.id }}"/>
                <input type="hidden" name="aid" value="{{ area.id }}"/>
                <div class="modal-body">
                  <div class="form-group">
                      <div class="input-group">
                          <span class="input-group-addon">服务器名称:</span>
                          <input name="name" class="form-control">
                      </div>
                  </div>

                </div>
                <div class="modal-footer clearfix">
                  <button type="submit" class="btn btn-primary">提交</button>
                </div>
            </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->


<div class="modal fade bs-example-modal-sm" id="del-user-modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">删除服务器 </h4>
            </div>
            <form action="{{ url_for('game.del_server')}}" method="post">
            <input type="hidden" name="gid" value="{{ game.id }}"/>
            <input type="hidden" name="aid" value="{{ area.id }}"/>
                <div class="modal-body">
                  是否确认删除这些区
                  <input type="hidden" id="gids" name="sids"/>
                </div>
                <div class="modal-footer clearfix">
                  <button type="submit" class="btn btn-primary">提交</button>
                </div>
            </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->



<div class="modal fade" id="edit-user-modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">编辑服务器 </h4>
            </div>
            <form action="{{ url_for('game.update_server')}}" method="post">
                <input type="hidden" name="gid" value="{{ game.id }}"/>
                <input type="hidden" name="aid" value="{{ area.id }}"/>
                <input name="id" value="" type="hidden" id="edit-id">
                <div class="modal-body">
                  <div class="form-group">
                      <div class="input-group">
                          <span class="input-group-addon">服务器名称:</span>
                          <input name="name" id="edit-name" class="form-control">
                      </div>
                  </div>
                 
                  
                </div>
                <div class="modal-footer clearfix">
                  <button type="submit" class="btn btn-primary">提交</button>
                </div>
            </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->


{% endblock %}

{% block foot_js %}
    {{ super() }}

<script type="text/javascript">
     $(function() {
        /*
       $(".sidebar-menu > li").removeClass('active');
       $(".sidebar-menu > li").each(
         function(index,element){
           if(index==0){
             //alert(item);
             $(element).addClass('active');
           }
         }
       );
       $(".sidebar .treeview").tree();
       */
       
       //用户table操作
      $(".check-all").on("change",function(event){
         if($(this).prop('checked')){
           $(".check-item").prop('checked',true);
         }else{
           $(".check-item").prop('checked',false);
         }
       });
       
       
       $(".edit-user").on("click",function(){
         selected_id = $(this).parent().siblings().find(':checkbox').val()
         $.getJSON('/game/_get_server/'+selected_id,function(data){
            $('#edit-id').val(data.id);
            $('#edit-name').val(data.username);
            $('#edit-user-modal').modal();
         });
       });
       
       
       $(".mutiple-delete-user").on("click",function(){
         var item_size = $(".check-item").size();
         var checked_item_size = 0;
         var checked_items = new Array();
         $(".check-item").each(function(index,element){
           if(element.checked){
             checked_item_size++;
             checked_items.push(element);
           }
         });
         if(checked_item_size == 0){
           alert("至少选择一个需要删除的项目");
         }else{            
            uids = $(checked_items).map(function(){return $(this).val()}).get().join();
            $('#gids').val(uids);
            $('#del-user-modal').modal();
         }
       });
      
     });
   </script>

{% endblock %}