app/dic/__init__.py
from flask import Blueprint

dic = Blueprint('dic',__name__)

from . import views

app/dic/views.py
#coding=utf-8
from flask import render_template, session, redirect, url_for, current_app
from flask import jsonify
from flask import request
from flask.ext.login import login_required
from ..models import OrderType,IssueType,GroupTask
from .. import db
from . import dic

#订单类型管理
@dic.route('/ordertypes')
@login_required
def ordertypes():
	ordertypes = OrderType.query.order_by('id').all()
	return render_template('dic/order_types.html',ordertypes=ordertypes)

@dic.route('/add_ordertype',methods=['POST'])
@login_required
def add_ordertype():
	ordertype = OrderType(name=request.form['name'],color=request.form['color'])
	db.session.add(ordertype)
	db.session.commit()
	return redirect(url_for('dic.ordertypes'))

@dic.route('/del_ordertype',methods=['POST'])
@login_required
def del_ordertype():
	gids = request.form['gids']
	OrderType.query.filter(OrderType.id.in_(gids.split(','))).delete(synchronize_session=False)
	return redirect(url_for('dic.ordertypes'))

@dic.route('/update_ordertype',methods=['POST'])
@login_required
def update_ordertype():
	gid = request.form['id']
	name = request.form['name']
	color = request.form['color']
	OrderType.query.filter_by(id=gid).update({OrderType.name:name, OrderType.color:color})
	db.session.commit()
	return redirect(url_for('dic.ordertypes'))

@dic.route('/_get_ordertype/<gid>')
def get_ordertype(gid):
	ordertype = OrderType.query.filter_by(id=gid).first()
	return jsonify(ordertype.to_json())


#异常类型管理
@dic.route('/issuetypes')
@login_required
def issuetypes():
	issuetypes = IssueType.query.order_by('id').all()
	return render_template('dic/issue_types.html',issuetypes=issuetypes)

@dic.route('/add_issuetype',methods=['POST'])
@login_required
def add_issuetype():
	issuetype = IssueType(name=request.form['name'])
	db.session.add(issuetype)
	db.session.commit()
	return redirect(url_for('dic.issuetypes'))

@dic.route('/del_issuetype',methods=['POST'])
@login_required
def del_issuetype():
	gids = request.form['gids']
	IssueType.query.filter(IssueType.id.in_(gids.split(','))).delete(synchronize_session=False)
	return redirect(url_for('dic.issuetypes'))

@dic.route('/update_issuetype',methods=['POST'])
@login_required
def update_issuetype():
	gid = request.form['id']
	name = request.form['name']
	IssueType.query.filter_by(id=gid).update({IssueType.name:name})
	db.session.commit()
	return redirect(url_for('dic.issuetypes'))

@dic.route('/_get_issuetype/<gid>')
def get_issuetype(gid):
	issuetype = IssueType.query.filter_by(id=gid).first()
	return jsonify(issuetype.to_json())


#任务类型管理
@dic.route('/tasktypes')
@login_required
def tasktypes():
	tasktypes = GroupTask.query.order_by('id').all()
	return render_template('dic/group_tasks.html',tasktypes=tasktypes)

@dic.route('/add_tasktype',methods=['POST'])
@login_required
def add_tasktype():
	tasktype = GroupTask(type=request.form['type'],name=request.form['name'])
	db.session.add(tasktype)
	db.session.commit()
	return redirect(url_for('dic.tasktypes'))

@dic.route('/del_tasktype',methods=['POST'])
@login_required
def del_tasktype():
	gids = request.form['gids']
	GroupTask.query.filter(GroupTask.id.in_(gids.split(','))).delete(synchronize_session=False)
	return redirect(url_for('dic.tasktypes'))

@dic.route('/update_tasktype',methods=['POST'])
@login_required
def update_tasktype():
	gid = request.form['id']
	name = request.form['name']
	type=request.form['type']
	GroupTask.query.filter_by(id=gid).update({GroupTask.name:name,GroupTask.type:type})
	db.session.commit()
	return redirect(url_for('dic.tasktypes'))

@dic.route('/_get_tasktype/<gid>')
def get_tasktype(gid):
	tasktype = GroupTask.query.filter_by(id=gid).first()
	return jsonify(tasktype.to_json())

app/order/__init__.py
from flask import Blueprint

order = Blueprint('order',__name__)

from . import views

app/order/views.py
#coding=utf-8
from flask import render_template, session, redirect, url_for, current_app
from flask import jsonify
from flask import request,Response
from flask.ext.login import login_required,current_user
from ..models import OrderType,IssueType,Order,Area,OrderProcess,OrderStatus,OrderGroup,WarningType,OrderWarning
from datetime import datetime
from .. import db
from . import order
import xlwt
import StringIO
import mimetypes
from werkzeug.datastructures import Headers

#订单处理中心
@order.route('/')
@login_required
def orders():
	ordertypes = OrderType.query.order_by('id').all()
	issuetypes = IssueType.query.order_by('id').all()
	warninges = WarningType.query.order_by('id').all()
	areas = Area.query.order_by('id').all()
	status = OrderStatus.query.order_by('id').all()
	order_query = Order.query.filter_by(is_delete=0)
	order_no = request.args.get('order_no')
	if order_no:
		order_query = order_query.filter_by(order_no=order_no)
	acter_name = request.args.get('acter_name')
	if acter_name:
		order_query = order_query.filter_by(acter_name=acter_name)
	area_id = request.args.get('area_id')
	if area_id and area_id !='0':
		order_query = order_query.filter_by(area_id=area_id)
	status_id = request.args.get('status_id')
	if status_id and status_id !='0':
		order_query = order_query.filter_by(status_id=status_id)
	else:
		order_query = order_query.filter(Order.status_id != 11)
	type_id = request.args.get('type_id')
	if type_id and type_id !='0':
		order_query = order_query.filter_by(type_id=type_id)
	is_issue = request.args.get('is_issue')
	if is_issue:
		order_query = order_query.filter_by(is_issue=is_issue)
	wangwang = request.args.get('wangwang')
	if wangwang:
		order_query = order_query.filter_by(wangwang=wangwang)
	mobile = request.args.get('mobile')
	if mobile:
		order_query = order_query.filter_by(mobile=mobile)


	orders = order_query.order_by('id desc').all()


	return render_template('order/index.html',ordertypes=ordertypes,issuetypes=issuetypes,orders=orders,areas=areas,status=status,warninges=warninges)

@order.route('/add_order',methods=['POST'])
@login_required
def add_order():
	type_id = request.form['type_id']
	area_id = request.form['area_id']
	acter_name = request.form['acter_name']
	acter_account = request.form['acter_account']
	acter_password = request.form['acter_password']
	start_level = request.form['start_level']
	end_level = request.form['end_level']
	wangwang = request.form['wangwang']
	qq = request.form['qq']
	mobile = request.form['mobile']
	amount = request.form['amount']
	paytype = request.form['paytype']
	memo = request.form['memo']
	warning_type = request.form['warning_type']
	taobao_date = request.form['taobao_date']
	order = Order(type_id=int(type_id),area_id=int(area_id),acter_name=acter_name, \
		            acter_account=acter_account,acter_password=acter_password, \
		            start_level=start_level,end_level=end_level,now_level=start_level, \
		            wangwang=wangwang,qq=qq,mobile=mobile,amount=amount, \
		            paytype=paytype,memo=memo,warning_type=warning_type,taobao_date=taobao_date)
	order.status_id=1
	order.create_man = current_user.id
	order.init_order_no()
	db.session.add(order)
	db.session.commit()
	OrderWarning.save(order.id,warning_type,memo,current_user.id)
	OrderProcess.save(order.id,current_user.id,"新增订单")
	return redirect(request.referrer)

@order.route('/update_order',methods=['POST'])
@login_required
def update_order():
	gid = request.form['id']
	type_id = request.form['type_id']
	area_id = request.form['area_id']
	acter_name = request.form['acter_name']
	acter_account = request.form['acter_account']
	acter_password = request.form['acter_password']
	start_level = request.form['start_level']
	end_level = request.form['end_level']
	wangwang = request.form['wangwang']
	qq = request.form['qq']
	mobile = request.form['mobile']
	amount = request.form['amount']
	paytype = request.form['paytype']
	memo = request.form['memo']
	taobao_date = request.form['taobao_date']
	Order.query.filter_by(id=gid).update({Order.type_id:type_id,Order.area_id:area_id,Order.acter_name:acter_name, \
										  Order.acter_account:acter_account,Order.acter_password:acter_password, \
										  Order.start_level:start_level,Order.end_level:end_level,Order.wangwang:wangwang, \
										  Order.qq:qq,Order.mobile:mobile,Order.amount:amount,Order.paytype:paytype, \
										  Order.memo:memo,Order.update_man:current_user.id,Order.update_date:datetime.now(),Order.taobao_date:taobao_date})
	db.session.commit()
	OrderProcess.save(gid,current_user.id,"修改订单")
	return redirect(request.referrer)

@order.route('/del_order',methods=['POST'])
@login_required
def del_order():
	gids = request.form['gids']
	Order.query.filter(Order.id.in_(gids.split(','))).update({Order.is_delete:1},synchronize_session=False)
	db.session.commit()
	
	return redirect(request.referrer)


@order.route('/check_order',methods=['POST'])
@login_required
def check_order():
	oid = request.form['oid']
	Order.query.filter_by(id=oid).update({Order.status_id:2,Order.update_date:datetime.now(),Order.update_man:current_user.id})
	db.session.commit()
	OrderProcess.save(oid,current_user.id,"审核订单")
	return redirect(request.referrer)

@order.route('/bug_order',methods=['POST'])
@login_required
def bug_order():
	oid = request.form['oid']
	issue_type = request.form['issue_type']
	issue_memo = request.form['issue_memo']
	Order.query.filter_by(id=oid).update({Order.is_issue:1,Order.issue_id:issue_type,Order.issue_memo:issue_memo, \
										  Order.update_date:datetime.now(),Order.update_man:current_user.id})
	db.session.commit()

	OrderProcess.save(oid,current_user.id,u"标记为异常订单 异常信息为: %s" %issue_memo)
	return redirect(request.referrer)

@order.route('/unbug_order',methods=['POST'])
@login_required
def unbug_order():
	oid = request.form['oid']
	Order.query.filter_by(id=oid).update({Order.is_issue:0,Order.issue_id:None,Order.issue_memo:"", \
										  Order.update_date:datetime.now(),Order.update_man:current_user.id})
	db.session.commit()
	OrderProcess.save(oid,current_user.id,"解除异常")
	return redirect(request.referrer)

@order.route('/wait_task',methods=['POST'])
@login_required
def wait_task():
	gids = request.form['gids']
	Order.query.filter(Order.id.in_(gids.split(','))).update({Order.status_id:6},synchronize_session=False)
	for oid in gids.split(','):
		OrderProcess.save(oid,current_user.id,"修改状态至转任务组")
	db.session.commit()
	
	return redirect(request.referrer)

@order.route('/add_warning',methods=['POST'])
@login_required
def add_warning():
	oid = request.form['oid']
	warning_type = request.form['warning_type']
	content = request.form['content']

	Order.query.filter_by(id=oid).update({Order.warning_type:warning_type,Order.update_date:datetime.now(),Order.update_man:current_user.id},synchronize_session=False)
	db.session.commit()
	OrderWarning.save(oid,warning_type,content,current_user.id)
	
	return redirect(request.referrer)


@order.route('/complete_order',methods=['POST'])
@login_required
def complete_order():
	gids = request.form['gids']
	Order.query.filter(Order.id.in_(gids.split(','))).update({Order.status_id:10},synchronize_session=False)
	for oid in gids.split(','):
		OrderProcess.save(oid,current_user.id,"修改状态至已完成")
	db.session.commit()
	
	return redirect(request.referrer)

@order.route('/back_order_to_start',methods=['POST'])
@login_required
def back_order_to_start():
	gids = request.form['gids']
	Order.query.filter(Order.id.in_(gids.split(','))).update({Order.status_id:1,Order.group_id:None,Order.team_id:None},synchronize_session=False)
	for oid in gids.split(','):
		OrderProcess.save(oid,current_user.id,"修改状态至新订单")
	db.session.commit()
	
	return redirect(request.referrer)

@order.route('/notification_order',methods=['POST'])
@login_required
def notification_order():
	gids = request.form['gids']
	Order.query.filter(Order.id.in_(gids.split(','))).update({Order.status_id:11},synchronize_session=False)
	for oid in gids.split(','):
		OrderProcess.save(oid,current_user.id,"修改状态至已通知")
	db.session.commit()
	
	return redirect(request.referrer)

@order.route('/to_group',methods=['POST'])
def to_group():
	oid = request.form['oid'];
	tid = request.form['tid'];

	

	group = OrderGroup.query.filter_by(id=tid).first()

	Order.query.filter_by(id=oid).update({Order.group_id:tid,Order.status_id:group.status_id, \
										  Order.update_date:datetime.now(),Order.update_man:current_user.id})
	db.session.commit()
	if group.group_type == 0:
		OrderProcess.save(oid,current_user.id,u"订单加入 %s %s %s组" %(group.name,group.area.name,group.no))
	else:
		OrderProcess.save(oid,current_user.id,u"订单加入 %s %s组 %s号机" %(group.name,group.no,group.target))
	return redirect(request.referrer)


@order.route('/_get_order/<gid>')
def get_order(gid):
	order = Order.query.filter_by(id=gid).first()
	return jsonify(order.to_json())





@order.route('/export')
def export():
	order_query = Order.query.filter_by(is_delete=0)
	order_no = request.args.get('order_no')
	if order_no:
		order_query = order_query.filter_by(order_no=order_no)
	acter_name = request.args.get('acter_name')
	if acter_name:
		order_query = order_query.filter_by(acter_name=acter_name)
	area_id = request.args.get('area_id')
	if area_id and area_id !='0':
		order_query = order_query.filter_by(area_id=area_id)
	status_id = request.args.get('status_id')
	if status_id and status_id !='0':
		order_query = order_query.filter_by(status_id=status_id)
	type_id = request.args.get('type_id')
	if type_id and type_id !='0':
		order_query = order_query.filter_by(type_id=type_id)
	is_issue = request.args.get('is_issue')
	if is_issue and is_issue =='1':
		order_query = order_query.filter_by(is_issue=1)

	orders = order_query.order_by('id').all()
	response=Response()
	response.status_code=200
	workbook=xlwt.Workbook()
	sheet = workbook.add_sheet('A Test Sheet')
	sheet.write(0,0,u'单号')
	sheet.write(0,1,u'类型')
	sheet.write(0,2,u'状态')
	sheet.write(0,3,u'区服')
	sheet.write(0,4,u'角色')
	sheet.write(0,5,u'账号')

app/templates/dic/group_tasks.html
{% extends "layout.html" %}

{% block page_content %}

<!-- Right side column. Contains the navbar and content of the page -->
<aside class="right-side">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            任务类型管理
        </h1>
        <ol class="breadcrumb">
            <li><a href="{{ url_for('main.index') }}"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active"><a href="{{ url_for('dic.tasktypes') }}">任务类型管理</a></li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">

        <div class="row">
            <div class="col-md-12">
                <div class="box">
                      
                    <div class="box-body">
                        
                        <div class="box-header">
                            <h3 class="box-title">任务类型列表</h3>
                            <span class="pull-right">
                              <button type="button" class="btn btn-success" data-toggle="modal" data-target="#add-user-modal"><i class='fa fa-plus'></i></button>
                              <button type="button" class="btn btn-danger mutiple-delete-user"><i class='fa fa-trash-o'></i></button>
                            </span>
                        </div><!-- /.box-header -->
                        
                          <table class="table table-bordered table-hover">
                              <tr>
                                  <th style="width: 10px">
                                    <input type="checkbox" class="icheckbox_square-blue check-all"/>
                                  </th>
                                  <th style="width: 10px">#</th>
                                  <th>任务名称</th>
                                  <th>类型</th>
                                  
                                  <th style="width: 200px">操作</th>
                              </tr>

                              {% for tasktype in tasktypes %}
                              <tr>
                                  <td>
                                    <input type="checkbox" value="{{ tasktype.id }}" class="minimal-red check-item"/>
                                   
                                  </td>
                                  <td>{{ tasktype.id }}</td>
                                 
                                  <td>{{ tasktype.name }}</td>
                                  <td>
                                    {% if tasktype.type==0 %}团练{% else %}任务{% endif %}
                                  
                                  </td>
                                  
                                  <td>
                                    
                                        <button type="button" class="btn btn-default edit-user"><i class='fa fa-wrench'></i></button>

                                        
                                        </button>
                                       
                                   
                                  </td>
                              </tr>
                              {% endfor %}
                              
                              
                          </table>
                      </div><!-- /.box-body -->
                      
                  </div>
                </div>
                
                
              </div>
    </section><!-- /.content -->
</aside><!-- /.right-side -->

{% endblock %}

{% block otherdiv %}
 <!-- COMPOSE MESSAGE MODAL -->
<div class="modal fade" id="add-user-modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">新增任务类型 </h4>
            </div>
            <form action="{{ url_for('dic.add_tasktype')}}" method="post">
                <div class="modal-body">
                  <div class="form-group">
                      <div class="input-group">
                          <span class="input-group-addon">任务名称:</span>
                          <input name="name" class="form-control">
                      </div>
                  </div>
                  <div class="form-group">
                      <div class="input-group">
                          <span class="input-group-addon">类型:</span>
                          <select name="type"  class="form-control">
                            <option value="0">团练</option>
                            <option value="1">任务</option>
                          </select>
                      </div>
                  </div>

                </div>
                <div class="modal-footer clearfix">
                  <button type="submit" class="btn btn-primary">提交</button>
                </div>
            </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->


<div class="modal fade bs-example-modal-sm" id="del-user-modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">删除任务类型 </h4>
            </div>
            <form action="{{ url_for('dic.del_tasktype')}}" method="post">
                <div class="modal-body">
                  是否确认删除这些任务类型
                  <input type="hidden" id="gids" name="gids"/>
                </div>
                <div class="modal-footer clearfix">
                  <button type="submit" class="btn btn-primary">提交</button>
                </div>
            </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->



<div class="modal fade" id="edit-user-modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">编辑任务类型 </h4>
            </div>
            <form action="{{ url_for('dic.update_tasktype')}}" method="post">
                <input name="id" value="" type="hidden" id="edit-id">
                <div class="modal-body">
                  <div class="form-group">
                      <div class="input-group">
                          <span class="input-group-addon">任务名称:</span>
                          <input name="name" id="edit-name" class="form-control">
                      </div>
                  </div>
                  <div class="form-group">
                      <div class="input-group">
                          <span class="input-group-addon">类型:</span>
                          <select name="type" id="edit-type" class="form-control">
                            <option value="0">团练</option>
                            <option value="1">任务</option>
                          </select>
                      </div>
                  </div>
                 
                  
                </div>
                <div class="modal-footer clearfix">
                  <button type="submit" class="btn btn-primary">提交</button>
                </div>
            </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->


{% endblock %}

{% block foot_js %}
    {{ super() }}

<script type="text/javascript">
     $(function() {
        /*
       $(".sidebar-menu > li").removeClass('active');
       $(".sidebar-menu > li").each(
         function(index,element){
           if(index==0){
             //alert(item);
             $(element).addClass('active');
           }
         }
       );
       $(".sidebar .treeview").tree();
       */

       
       
       //用户table操作
       $(".check-all").on("change",function(event){
         if($(this).prop('checked')){
           $(".check-item").prop('checked',true);
         }else{
           $(".check-item").prop('checked',false);
         }
       });
       
       
       $(".edit-user").on("click",function(){
         selected_id = $(this).parent().siblings().find(':checkbox').val()
         $.getJSON('_get_tasktype/'+selected_id,function(data){
            $('#edit-id').val(data.id);
            $('#edit-name').val(data.name);
            $('#edit-type').val(data.type)
            $('#edit-user-modal').modal();
         });
       });
       
       
       $(".mutiple-delete-user").on("click",function(){
         var item_size = $(".check-item").size();
         var checked_item_size = 0;
         var checked_items = new Array();
         $(".check-item").each(function(index,element){
           if(element.checked){
             checked_item_size++;
             checked_items.push(element);
           }
         });
         if(checked_item_size == 0){
           alert("至少选择一个需要删除的项目");
         }else{            
            uids = $(checked_items).map(function(){return $(this).val()}).get().join();
            $('#gids').val(uids);
            $('#del-user-modal').modal();
         }
       });
      
     });
   </script>

{% endblock %}

app/templates/dic/issue_types.html
{% extends "layout.html" %}

{% block page_content %}

<!-- Right side column. Contains the navbar and content of the page -->
<aside class="right-side">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            异常类型管理
        </h1>
        <ol class="breadcrumb">
            <li><a href="{{ url_for('main.index') }}"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active"><a href="{{ url_for('dic.issuetypes') }}">异常类型管理</a></li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">

        <div class="row">
            <div class="col-md-12">
                <div class="box">
                      
                    <div class="box-body">
                        
                        <div class="box-header">
                            <h3 class="box-title">异常类型列表</h3>
                            <span class="pull-right">
                              <button type="button" class="btn btn-success" data-toggle="modal" data-target="#add-user-modal"><i class='fa fa-plus'></i></button>
                              <button type="button" class="btn btn-danger mutiple-delete-user"><i class='fa fa-trash-o'></i></button>
                            </span>
                        </div><!-- /.box-header -->
                        
                          <table class="table table-bordered table-hover">
                              <tr>
                                  <th style="width: 10px">
                                    <input type="checkbox" class="icheckbox_square-blue check-all"/>
                                  </th>
                                  <th style="width: 10px">#</th>
                                  <th>类型名称</th>
                                  
                                  <th style="width: 200px">操作</th>
                              </tr>

                              {% for issuetype in issuetypes %}
                              <tr>
                                  <td>
                                    <input type="checkbox" value="{{ issuetype.id }}" class="minimal-red check-item"/>
                                   
                                  </td>
                                  <td>{{ issuetype.id }}</td>
                                 
                                  <td>{{ issuetype.name }}</td>
                                  
                                  <td>
                                    
                                        <button type="button" class="btn btn-default edit-user"><i class='fa fa-wrench'></i></button>

                                        
                                        </button>
                                       
                                   
                                  </td>
                              </tr>
                              {% endfor %}
                              
                              
                          </table>
                      </div><!-- /.box-body -->
                      
                  </div>
                </div>
                
                
              </div>
    </section><!-- /.content -->
</aside><!-- /.right-side -->

{% endblock %}

{% block otherdiv %}
 <!-- COMPOSE MESSAGE MODAL -->
<div class="modal fade" id="add-user-modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">新增异常类型 </h4>
            </div>
            <form action="{{ url_for('dic.add_issuetype')}}" method="post">
                <div class="modal-body">
                  <div class="form-group">
                      <div class="input-group">
                          <span class="input-group-addon">类型名称:</span>
                          <input name="name" class="form-control">
                      </div>
                  </div>


                </div>
                <div class="modal-footer clearfix">
                  <button type="submit" class="btn btn-primary">提交</button>
                </div>
            </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->


<div class="modal fade bs-example-modal-sm" id="del-user-modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">删除异常类型 </h4>
            </div>
            <form action="{{ url_for('dic.del_issuetype')}}" method="post">
                <div class="modal-body">
                  是否确认删除这些异常类型
                  <input type="hidden" id="gids" name="gids"/>
                </div>
                <div class="modal-footer clearfix">
                  <button type="submit" class="btn btn-primary">提交</button>
                </div>
            </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->



<div class="modal fade" id="edit-user-modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">编辑异常类型 </h4>
            </div>
            <form action="{{ url_for('dic.update_issuetype')}}" method="post">
                <input name="id" value="" type="hidden" id="edit-id">
                <div class="modal-body">
                  <div class="form-group">
                      <div class="input-group">
                          <span class="input-group-addon">类型名称:</span>
                          <input name="name" id="edit-name" class="form-control">
                      </div>
                  </div>
                 
                  
                </div>
                <div class="modal-footer clearfix">
                  <button type="submit" class="btn btn-primary">提交</button>
                </div>
            </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->


{% endblock %}

{% block foot_js %}
    {{ super() }}

<script type="text/javascript">
     $(function() {
        /*
       $(".sidebar-menu > li").removeClass('active');
       $(".sidebar-menu > li").each(
         function(index,element){
           if(index==0){
             //alert(item);
             $(element).addClass('active');
           }
         }
       );
       $(".sidebar .treeview").tree();
       */

       
       
       //用户table操作
       $(".check-all").on("change",function(event){
         if($(this).prop('checked')){
           $(".check-item").prop('checked',true);
         }else{
           $(".check-item").prop('checked',false);
         }
       });
       
       
       $(".edit-user").on("click",function(){
         selected_id = $(this).parent().siblings().find(':checkbox').val()
         $.getJSON('_get_issuetype/'+selected_id,function(data){
            $('#edit-id').val(data.id);
            $('#edit-name').val(data.name);
            $('#edit-user-modal').modal();
         });
       });
       
       
       $(".mutiple-delete-user").on("click",function(){
         var item_size = $(".check-item").size();
         var checked_item_size = 0;
         var checked_items = new Array();
         $(".check-item").each(function(index,element){
           if(element.checked){
             checked_item_size++;
             checked_items.push(element);
           }
         });
         if(checked_item_size == 0){
           alert("至少选择一个需要删除的项目");
         }else{            
            uids = $(checked_items).map(function(){return $(this).val()}).get().join();
            $('#gids').val(uids);
            $('#del-user-modal').modal();
         }
       });
      
     });
   </script>

{% endblock %}