app/search/__init__.py
from flask import Blueprint

search = Blueprint('search',__name__)

from . import views

app/search/views.py
#encoding=utf-8
from flask import render_template, session, redirect, url_for, current_app
from flask import jsonify
from flask import request,Response
from flask.ext.login import login_required,current_user
from . import search
from datetime import date
from ..models import OrderType,IssueType,Area,OrderStatus,Order
from .. import db
import xlwt
import StringIO
import mimetypes
from werkzeug.datastructures import Headers

@search.route('/')
@login_required
def index():
    ordertypes = OrderType.query.order_by('id').all()
    issuetypes = IssueType.query.order_by('id').all()
    areas = Area.query.order_by('id').all()
    status = OrderStatus.query.order_by('id').all()
    order_query = Order.query.filter_by(is_delete=0)

    order_no = request.args.get('order_no')
    if order_no:
        order_query = order_query.filter_by(order_no=order_no)
    acter_name = request.args.get('acter_name')
    if acter_name:
        order_query = order_query.filter_by(acter_name=acter_name)

    wangwang = request.args.get('wangwang')
    if wangwang:
        order_query = order_query.filter_by(wangwang=wangwang)
    mobile = request.args.get('mobile')
    if mobile:
        order_query = order_query.filter_by(mobile=mobile)


    orders = list()
    if order_no or acter_name or wangwang or mobile:
        orders = order_query.order_by('id desc').all()


    return render_template('search/index.html',ordertypes=ordertypes,issuetypes=issuetypes,orders=orders,areas=areas,status=status)

@search.route('/export')
def export():
    order_query = Order.query.filter_by(is_delete=0)
    order_no = request.args.get('order_no')
    if order_no:
        order_query = order_query.filter_by(order_no=order_no)
    acter_name = request.args.get('acter_name')
    if acter_name:
        order_query = order_query.filter_by(acter_name=acter_name)
   
    wangwang = request.args.get('wangwang')
    if wangwang:
        order_query = order_query.filter_by(wangwang=wangwang)
    mobile = request.args.get('mobile')
    if mobile:
        order_query = order_query.filter_by(mobile=mobile)


    orders = order_query.order_by('id desc').all()
    response=Response()
    response.status_code=200
    workbook=xlwt.Workbook()
    sheet = workbook.add_sheet('A Test Sheet')
    sheet.write(0,0,u'单号')
    sheet.write(0,1,u'类型')
    sheet.write(0,2,u'状态')
    sheet.write(0,3,u'区服')
    sheet.write(0,4,u'角色')
    sheet.write(0,5,u'账号')
    sheet.write(0,6,u'密码')
    sheet.write(0,7,u'起点')
    sheet.write(0,8,u'需求')
    sheet.write(0,9,u'当前')
    sheet.write(0,10,u'旺旺')
    sheet.write(0,11,u'QQ号')
    sheet.write(0,12,u'电话')
    sheet.write(0,13,u'金额')
    sheet.write(0,14,u'支付')
    sheet.write(0,15,u'创建时间')

    index = 1;
    for order in orders:
        sheet.write(index,0,order.order_no)
        sheet.write(index,1,order.order_type.name)
        sheet.write(index,2,order.order_status.name)
        sheet.write(index,3,order.area.name)
        sheet.write(index,4,order.acter_name)
        sheet.write(index,5,order.acter_account)
        sheet.write(index,6,order.acter_password)
        sheet.write(index,7,order.start_level)
        sheet.write(index,8,order.end_level)
        sheet.write(index,9,order.now_level)
        sheet.write(index,10,order.wangwang)
        sheet.write(index,11,order.qq)
        sheet.write(index,12,order.mobile)
        sheet.write(index,13,order.amount)
        sheet.write(index,14,order.paytype)
        sheet.write(index,15,str(order.create_date))
        index = index+1;


    output = StringIO.StringIO()
    workbook.save(output)
    response.data = output.getvalue()

    filename = 'export.xls'
    mimetype_tuple = mimetypes.guess_type(filename)

    response_headers = Headers({
            'Pragma' : "public",
            'Expires' : '0',
            'Cache-Control': 'must-revalidate, post-check=0, pre-check=0',
            'Cache-Control': 'private',
            'Content-Type': mimetype_tuple[0],
            'Content-Disposition': 'attachment; filename=\"%s\";' % filename,
            'Content-Transfer-Encoding': 'binary',
            'Content-Length': len(response.data)
        })

    if not mimetype_tuple[1] is None:
        response.update({
                'Content-Encoding' : mimetype_tuple[1]
            })

    response.headers = response_headers

    return response

app/templates/search/index.html
{% extends "layout.html" %}

{% block page_content %}

<!-- Right side column. Contains the navbar and content of the page -->
<aside class="right-side">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            订单查询中心
        </h1>
        <ol class="breadcrumb">
            <li><a href="{{ url_for('main.index') }}"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active"><a href="{{ url_for('search.index') }}">订单查询中心</a></li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">

        <div class="box box-solid">
          <div class="box-body">
             <form action="{{ url_for('search.index') }}" method="get">
             <div class="form-inline">
              <div class="input-group">
                          <span class="input-group-addon">订单号:</span>
                          <input name="order_no" value="{% if request.args.get('order_no') != None %}{{ request.args.get('order_no') }}{% endif %}" class="form-control">
              </div>
              <div class="input-group">
                          <span class="input-group-addon">角色名:</span>
                          <input name="acter_name" value="{% if request.args.get('acter_name') != None %}{{ request.args.get('acter_name') }}{% endif %}" class="form-control">
              </div>
             
             
            
              
             </div>
             <div class="form-inline inline-form-magin">

             
               <div class="input-group">
                          <span class="input-group-addon">旺旺:</span>
                          <input name="wangwang" value="{% if request.args.get('wangwang') != None %}{{ request.args.get('wangwang') }}{% endif %}" class="form-control">
              </div>
              <div class="input-group">
                          <span class="input-group-addon">手机:</span>
                          <input name="mobile" value="{% if request.args.get('mobile') != None %}{{ request.args.get('mobile') }}{% endif %}" class="form-control">
              </div>
              <div class="pull-right">
              <button class="btn btn-warning">查询</button>
              </div>
              </div>
             </form>
          </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="box">
                      
                    <div class="box-body">
                        
                        <div class="box-header">
                            <h3 class="box-title">订单处理列表</h3>
                            <span class="pull-right">
                             
                            
                              <form action="{{ url_for('search.export') }}" method="get" style="margin:0px;display: inline">
                              <input type="hidden" name="order_no" value="{% if request.args.get('order_no') != None %}{{ request.args.get('order_no') }}{% endif %}">
                              <input type="hidden" name="acter_name" value="{% if request.args.get('acter_name') != None %}{{ request.args.get('acter_name') }}{% endif %}">
                                <input type="hidden" name="wangwang" value="{% if request.args.get('wangwang') != None %}{{ request.args.get('wangwang') }}{% endif %}">
                                  <input type="hidden" name="mobile" value="{% if request.args.get('mobile') != None %}{{ request.args.get('mobile') }}{% endif %}">
                            
                              <button class="btn btn-primary"><i class='fa fa-save'></i></button>
                                
                              </form>
                             
                               

                              

                            </span>
                        </div><!-- /.box-header -->
                        
                          <table class="table table-bordered table-hover">
                              <tr>
                                  
                                  <th>单号</th>
                                  <th>类型</th>
                                  <th>状态</th>
                                  <th>区服</th>
                                  <th>角色</th>
                                  {% if user.role.id !=10 %}
                                  <th>账号</th>
                                  <th>密码</th>
                                  {% endif %}
                                  <th>起点</th>
                                  <th>需求</th>
                                  <th>当前</th>
                                  <th>旺旺</th>
                                  <th>QQ号</th>
                                  <th>电话</th>
                                  <th>金额</th>
                                  <th>支付</th>
                                  <th>创建</th>
                                  <th>操作</th>
                                  

                                  
                              </tr>

                              {% for order in orders %}
                              <tr style="background-color: {% if order.is_issue %} #ff0000  {% else %} {{ order.order_type.color }}  {% endif %}">
                                  
                                 
                                  <td>{{ order.order_no}}</td>
                                  <td>{{ order.order_type.name}}</td>
                                  <td>{{ order.order_status.name}}</td>
                                  <td>{{ order.area.name}}</td>
                                  <td>{{ order.acter_name }}</td>
                                  {% if user.role.id !=10 %}
                                  <td>{{ order.acter_account }}</td>
                                  <td>{{ order.acter_password }}</td>
                                  {% endif %}
                                  <td>{{ order.start_level }}</td>
                                  <td>{{ order.end_level }}</td>
                                  <td>{{ order.now_level }}</td>
                                  <td>{{ order.wangwang }}</td>
                                  <td>{{ order.qq }}</td>
                                  <td>{{ order.mobile }}</td>
                                  <td>{{ order.amount }}</td>
                                  <td>{{ order.paytype }}</td>
                                  <td>{{ order.create_date }}</td>
                                  <td>
                                      <button type="button" class="btn btn-default view-order" data-oid="{{ order.id }}">
                                        <i class='fa fa-wrench'></i>
                                      </button>

                                  </td>
                                  
                              </tr>
                              {% endfor %}
                              
                              
                          </table>
                      </div><!-- /.box-body -->
                      
                  </div>
                </div>
                
                
              </div>
    </section><!-- /.content -->
</aside><!-- /.right-side -->

{% endblock %}

{% block otherdiv %}

<div class="modal fade bs-example-modal-sm" id="view-order-modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-big-max">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">订单信息 </h4>
            </div>
            <div class="modal-body order-info">
                
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->


{% endblock %}

{% block foot_js %}
    {{ super() }}

<script type="text/javascript">
     $(function() {
       
       
      

       $('.datepicker').datepicker({language:'zh-CN'});

       //$('#start-date').val(moment().format('YYYY-MM-DD'));
       //$('#end-date').val(moment().format('YYYY-MM-DD'));

       //$('#search-daterange').val(moment().format('YYYY-MM-DD')+ " - "+moment().format('YYYY-MM-DD'));
       
       
       $('#search-daterange').daterangepicker({
          format:'YYYY-MM-DD',
          locale: { cancelLabel: '取消',
                  applyLabel: '应用',
                  monthNames:['一月','二月','三月','四月','五月','六月','七月','八月','九月','十月','十一月','十二月'],
                  daysOfWeek:['日','一','二','三','四','五','六'],
                  firstDay:1

                  } 
          },function(start, end, label) {
                  $('#start-date').val(start.format('YYYY-MM-DD'));
                  $('#end-date').val(end.format('YYYY-MM-DD'));
        });

       $(".view-order").on("click",function(event){
            var order_id = $(this).attr("data-oid");
            $.get('/order/__get_info/'+order_id,function(data){
                $('.order-info').html(data);
            });
            $("#view-order-modal").modal();
        });
    

      
     });
   </script>

{% endblock %}